const leads = [
  {
    id: 1,
    name: "Rahul",
    status: "new",
    agent: "John",
    source: "Referral",
    priority: "high",
    timeToClose: 30,
    comments: [],
  },
  {
    id: 2,
    name: "Priya",
    status: "contacted",
    agent: "Sarah",
    source: "Website",
    priority: "medium",
    timeToClose: 20,
    comments: [],
  },
  {
    id: 3,
    name: "Amit",
    status: "new",
    agent: "Mike",
    source: "Cold Call",
    priority: "low",
    timeToClose: 15,
    comments: [],
  },
  {
    id: 4,
    name: "Sneha",
    status: "contacted",
    agent: "John",
    source: "Website",
    priority: "medium",
    timeToClose: 25,
    comments: [],
  },
  {
    id: 5,
    name: "Rohit",
    status: "qualified",
    agent: "Sarah",
    source: "Referral",
    priority: "medium",
    timeToClose: 18,
    comments: [],
  },
  {
    id: 6,
    name: "Neha",
    status: "new",
    agent: "Mike",
    source: "Social Media",
    priority: "medium",
    timeToClose: 35,
    comments: [],
  },
  {
    id: 7,
    name: "Karan",
    status: "qualified",
    agent: "John",
    source: "Cold Call",
    priority: "low",
    timeToClose: 22,
    comments: [],
  },
  {
    id: 8,
    name: "Pooja",
    status: "qualified",
    agent: "Sarah",
    source: "Website",
    priority: "medium",
    timeToClose: 16,
    comments: [],
  },
  {
    id: 9,
    name: "Arjun",
    status: "contacted",
    agent: "Mike",
    source: "Referral",
    priority: "low",
    timeToClose: 28,
    comments: [],
  },
  {
    id: 10,
    name: "Meera",
    status: "qualified",
    agent: "John",
    source: "Social Media",
    priority: "high",
    timeToClose: 12,
    comments: [],
  },
];

export default leads;